export enum PERMISSIONS {
  SCHOOL = 'school',
  SCHOOL_EDIT = 'school-edit',
  SCHOOL_ACCEPT = 'school-accept',
  PARTICIPANT = 'participant',
  PARTICIPANT_EDIT = 'participant-edit',
  TRANSACTION = 'transaction',
  TRANSACTION_EDIT = 'transaction-edit',
  REGION = 'region',
  REGION_EDIT = 'region-edit',
  SETTING = 'setting',
  USER = 'users',
  USER_EDIT = 'users-edit',
  ADMIN = 'admin',
  ADMIN_EDIT = 'admin-edit',
  ADMIN_REGION = 'adminregion',
}
